version: '3'
services:
  php:
    image: liveart/php-sample-services
    container_name: liveart_php_sample_services
    volumes:
    - c:/Users/Public/docker-mounts/php-sample-services/files:/var/www/html/files
    restart: always
    networks:
    - liveartjs-lacp
  admin_area:
    image: liveart/admin-area
    container_name: liveart_admin_area
    depends_on:
    - php
    ports:
    - 3000:3000
    restart: always
    env_file:
    - ./Docker/liveartjs-lacp.env
    networks:
    - liveartjs-lacp
    volumes:
    - c:/Users/Public/docker-mounts/admin-area/files:/app/client/public/files
networks:
  liveartjs-lacp:
    driver: bridge
