version: '3'
services:
  designer:
    image: liveart/designer
    container_name: liveart_designer
    depends_on:
      - mongodb
      - admin_area
    ports:
      - 9000:80
    volumes:
    - /var/docker-mounts/designer:/var/www/html/files
    restart: always
    networks:
      - liveartjs-lacp
  admin_area:
    image: liveart/admin-area
    container_name: liveart_admin_area
    volumes:
      - /var/docker-mounts/admin_area:/app/
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    restart: always
    env_file:
      - ./Docker/liveartjs-lacp.env
    networks:
      - liveartjs-lacp
  mongodb:
    image: mongo
    container_name: liveart_mongo
    volumes:
      - /var/docker-mounts/liveartjs-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: yXptf19N2A86G8OxNpVyN6Lphf92MJWu
    restart: always
    networks:
      - liveartjs-lacp
networks:
  liveartjs-lacp:
    driver: bridge
